language: cpp 
dist: focal
compiler: gcc
os: linux
sudo: true
env:
    - BUILD_TYPE=Debug

# default gcc for Ubuntu Focal is v9, upgraded to v10 here
# It increases build time by ~1 min
addons:
        apt:
              sources:
                  - sourceline: “ppa:ubuntu-toolchain-r/test”
              packages:
                  - gcc-10
                  - g++-10
install:
# /usr/bin/gcc points to an older compiler on Linux.
- if [ "$CXX" = "g++" ]; then export CXX="g++-10" CC="gcc-10"; fi
script: 
  - ./build.sh
