name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2

    - name: Install build dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-wxWidgets mingw-w64-x86_64-graphviz


    - name: Build
      run: |
        g++ -I${{ github.workspace }}/dep/win/lib/gcc_lib/mswu -I${{ github.workspace }}/dep/win/include -IC:\\Program Files\\Graphviz\\include -I${{ github.workspace }}/libs/json/include -c $("dir" -Path ${{ github.workspace }}/src -Filter *.cpp -Recurse | %{$_.FullName}) -g -Wall -D_WINDOWS -D_UNICODE -D__WXMSW__ -DNDEBUG -DNOPCH
        g++ -L${{ github.workspace }}/dep/win/lib/gcc_lib -LC:\\Program Files\\Graphviz\\lib -Lc:\\mingw-w64\\mingw64\\x86_64-w64-mingw32\\lib -mwindows -static ${{ github.workspace }}/out/**/*.o -o ${{ github.workspace }}/exec/myapp.exe -lwxmsw31u_core -lwxbase31u -lwxpng -lcomdlg32 -lgdi32 -lcomctl32 -lole32 -loleaut32 -ldmoguids -luuid -lwinspool -lz -lwxregexu -lwxzlib -luxtheme -loleacc -lshlwapi -lversion -lgvc -lcgraph
